### ISSUE TITLE
Tree of uint64 instead of int64

### ISSUE THREAD

**Issue by gpip** [fake-name/IntraArchiveDeduplicator#3]
Hi,

Given a 64 bit descriptor like the following

```
descr = "1000000000000000000000000000000000000000000000000000000000000000"
assert len(descr) == 64
```

it seems there's no way to insert it correctly:

```
>>> int(descr, 2)
9223372036854775808L
>>> explicitSignCast(int(descr, 2))
0
```

That is, both `000...000` and `100..000` would be inserted as the number 0, `000...001` and `100...001` as the number 1, and so on. Does this mean the tree as it stands right now should be used with 63 bits descriptors instead?

Thank you

**Comment by gpip** [comment]
Oh, I just noticed that on your tests you're using `bitstring.Bits`, which would produce -9223372036854775808 for that `descr`. I guess I should avoid using explicitSignCast in that case?

**Comment by fake-name** [comment]
Ahhh sign conversion issues, my old friend.

I'm kind of stuck with `int64_t` as my base datatype, as it's the biggest integral type I can stuff into postgres. 

I'm not too sure what's going on with the hamming dist call. [I have tests](https://github.com/fake-name/IntraArchiveDeduplicator/blob/master/Tests/Test_BKTree.py#L166) for numbers around zero. Lemme put some more test cases together this evening.

**Comment by gpip** [comment]
Yes, why not :)

I did another quick test here, outside Vagrant that `hamming_dist` call returns 1 as expected, but inside Vagrant it returns 0. Uh..

**Comment by fake-name** [comment]
Whooo! Platform specific issues! Huzzah!

I'd be interested in whether `python3 -m nose Tests.Test_BKTree` and  `python3 -m nose Tests.Test_BKTree_2` pass. There are some unit tests in there that try to expose any sign-conversion issues.

**Comment by gpip** [comment]
On my non-virtual machine all the tests pass after I change the bitstring usage to `hamDb.explicitSignCast(int(binaryStringIn, 2))` (otherwise all the tests fail with `ValueError: Hashes must be an integer! Passed value '0', type '<type 'long'>'`).

Under Vagrant several tests fail, e.g.:

```
self = <test_bktree_2.TestSequenceFunctions_TallTree testMethod=test_3>

    def test_3(self):
        tgtHash = "1000000000000000000000000000000000000000000000000000000000000000"
        tgtHash = b2i(tgtHash)
        ret = self.tree.getWithinDistance(tgtHash, 0)
>       self.assertEqual(ret, set((64, )))
E       AssertionError: Items in the first set but not the second:
E       0

test/test_bktree_2.py:232: AssertionError
```

```
self = <test_bktree.TestSequenceFunctions testMethod=test_distance_f>

    def test_distance_f(self):
    
        v1 = b2i("0000000000000000000000000000000000000000000000000000000000000000")
        v2 = b2i("1111111111111111111111111111111111111111111111111111111111111111")
        v3 = b2i("0000000000000000000000000000000000000001111111111111111000000000")
        v4 = b2i("1000000000000000000000000000000000000000000000000000000000000000")
        v5 = b2i("0000000000000000000000000000000000000000000000000000000000000001")
        v6 = b2i("1100000000000000000000000000000000000000000000000000000000000000")
>       self.assertEqual(hamDb.f_hamming_dist(v1, v2), 64)
E       AssertionError: 45 != 64

test/test_bktree.py:156: AssertionError
```

(it's very likely the lines don't match exactly, I copied your tests to https://github.com/gpip/cBKTree/tree/master/test)

**Comment by fake-name** [comment]
Is it possible the vagrant install is 32 bit?

I don't think this would work at all on a 32 bit system.

**Comment by gpip** [comment]
It's using the `wheezy64` image, `uname -m` returns "x86_64", `uname -a` returns "Linux wheezy64 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u3 x86_64 GNU/Linux". Didn't see any warnings during the build, tried removing all the flags, and also built with debug flags, but got the same issue.

**Comment by fake-name** [comment]
Well WTH.

I'm having a go at converting the entire tree to unsigned `int`s, but I have no idea what's going on.

**Comment by fake-name** [comment]
Oh, what CPU are you running?

One thing I can think of is I'm using `__builtin_popcountll(x)` for counting bits in the distance bitfield. I'm not sure what it's support is on AMD processors (I have only intel servers - AMD servers are too expensive in terms of power).

**Comment by gpip** [comment]
Inside vagrant it reports the same CPU I have, a typical Intel(R) Core(TM) i7-4770HQ in a macbook (which has no issue running this out the vm). Maybe I'm tired, can't see what's causing this. FWIW, I ran this on a AWS box and got not issues, maybe it's not worth worrying about it.

**Comment by gpip** [comment]
I think the way to go about is to 1) not rely on explicitSign, use `bitstring.Bits(bin=...).int` instead, and 2) accept `(int, long)` for nodeHash for Python 2 compatibility.

**Comment by fake-name** [comment]
I assume that this codebase is reliable. If the sign-casting mechanic is behaving oddly, I want to know why. I'll keep poking around.

Python 2 compatibility is something I don't care about even a little bit. It's been 8 years, it's time to upgrade.

**Comment by fake-name** [comment]
Ok, I kind of suspect this is a python 3.2 issue. My testing targets are 3.4 and 3.5, and I've more or less moved away from systems with 3.4 entirely.

Why are you using a system with such an ancient version of python?

**Comment by gpip** [comment]
I ran these using Python 2.7, but let me test the latest patch release of 2.7 (because it ships with a very old one).

**Comment by fake-name** [comment]
That sounds reasonable to me.

How are you installing cython? Can you install a more recent version with a non-platform-sourced `pip`?

**Comment by fake-name** [comment]
@gpip  - If you're using this as a library, I'd strongly suggest you update if you need any concurrency support.

I discovered a issue where I had misunderstood the relationship between python threads and OS threads, leading to a potential issue where there could be lock-loss or lock-wedging. 

Basically, I was assuming that there was a direct mapping between python threads and OS threads (supported by the fact that python seems to create an additional OS thread for each python thread you instantiate.

Apparently this is not true, and python actually swaps execution between separate threads within the same OS pid. This means that my prior use of the `pthread` `rwlock` primitive could lead to situations where a lock can be repeatedly acquired or released from a single OS thread.

In any event, I reverted to an earlier, albeit less theoretically performant python rwlock implementation that handles the python threading behaviour correctly.
