### ISSUE TITLE
Usage/Example of Bk Tree

### ISSUE THREAD

**Issue by JunedKhan101** [fake-name/IntraArchiveDeduplicator#6]
I am developing a software where I will find and remove duplicates or similar images.

I did some research and found that Bk Trees should be a good data strucutre as I am gonna create perceptual hashes of images and I need to be able to compare the distance of hashes in the Bk tree which translates to the similarity of the images to be compared.

I looked at the file: https://github.com/fake-name/IntraArchiveDeduplicator/blob/master/deduplicator/bktree.hpp
however I'm unclear how I am supposed to create hashes and be able to compare them.

I think adding some examples on usage of Bk Tree in the readme would be helpful.

**Comment by fake-name** [comment]
Creating the hashes is left up to the user, as there are a large variety of hashes that are compatible.  It basically works with any hashing operation where the hamming distance between resulting hashes forms a metric space. This is *not* limited to just image perceptual hashes. 

In this case, the actual image hashing functions I use are here: https://github.com/fake-name/IntraArchiveDeduplicator/blob/master/scanner/hashFile.py. Functionally, it's a vendored version of https://github.com/JohannesBuchner/imagehash, though I made some changes (that library seems to want to store everything as a string, which I think is stupid. They're `int64`s in the database, so they should be `int64`s in my code).

I **do** assume the user has some understanding of how perceptual hashes work, and I'm not too interested in writing a introduction to the topic. https://www.hackerfactor.com/blog/?/archives/432-Looks-Like-It.html is a good place to start, though  There are lots of them out there. Here's one that even uses my postgres extension: https://github.com/KDJDEV/imagehash-reverse-image-search-tutorial

In all cases, unless you're doing ephemeral comparisons, you should really look at https://github.com/fake-name/pg-spgist_hamming. It
